### ISSUE TITLE
[Feature Request] Draggable overlay, Overlay format and Copy button

### ISSUE THREAD

**Issue by AxoCode** [AMereBagatelle/MCG#11]
**Draggable overlay** :

So you can drag the overlay. Why? Because currently, the overlay is below the chat. Or it's to hard to implement. Maybe just add a config that let you set the x and y of the overlay

**Overlay format** :

So you can set the format of the overlay. This is the available option :

`%name` is for the name
`%description` is for the description
`%x` is for the x
`%y` is for the y
`%z` is for the z

And the default format is :
```
%name @ %x %y %z
```

**Copy button** :

So there is a copy button when you highlight the coordinate. And there is a config for the format. The available option and the default format is the same as the overlay format. See above (Overlay format) to see the option and the default.

**Comment by AMereBagatelle** [comment]
The latest commit (234d3cf) adds the overlay positioning configuration screen, it is a simple X and Y config.

**Comment by AMereBagatelle** [comment]
The next latest commits now add a overlay format and copy button, not implemented to all the specifics that are detailed here, but close enough that I feel comfortable closing the feature request.
