### ISSUE TITLE
[Feature Request] make MCG remember what file i had open in what world last

### ISSUE THREAD

**Issue by KraXen72** [AMereBagatelle/MCG#16]
so i don't have to do extra click on file extra click on file when i want to quickly see or add a coordinate.

for example if i open file 1 in world 1 and file 2 in world 2, next time i play world 1 it would automatically open file 1. you could always go back ofcourse.

**Comment by AMereBagatelle** [comment]
I don't think it would be practical to store across world play sessions, but during a single play session I absolutely agree.

**Comment by KraXen72** [comment]
this is the quickest issue reply i ever got! thank you! if not across world play sessions, maybe just remember the last one i opened? or like once i open a file it will not close unless i either disconnect from server or save and quit to title

**Comment by AMereBagatelle** [comment]
By single play session, I mean as long as you are ingame (inside a world or server) it will remember which one you opened.  It won't close until you leave the world or server or manually back out.

**Comment by AMereBagatelle** [comment]
Added in [fe9453b0377a0bf0904d0d6774d618646fd1c79f](https://github.com/AMereBagatelle/MCG/commit/fe9453b0377a0bf0904d0d6774d618646fd1c79f)

**Comment by KraXen72** [comment]
epic! now please just build this and publish on modrinth! thank you!
