### ISSUE TITLE
Y and Z coordinates switch places

### ISSUE THREAD

**Issue by DragonEggBedrockBreaking** [AMereBagatelle/MCG#6]
Y and Z coordinates switch places when I input co-ords and save.

Expected behaviour:
- Y refers to height and Z to one of the horizontal axes.
- Y and Z don't switch places

Occurring behaviour:

![image](https://user-images.githubusercontent.com/68545280/102012539-fc99b600-3d42-11eb-8739-1a017386faab.png)

![image](https://user-images.githubusercontent.com/68545280/102012548-07ece180-3d43-11eb-91c6-eaa8f2f0726d.png)

After teleporting to those co-ordinates through the gui:
![image](https://user-images.githubusercontent.com/68545280/102012578-2521b000-3d43-11eb-97f1-f89961eefa9b.png)

**Comment by AMereBagatelle** [comment]
Fixed in next release

**Comment by DragonEggBedrockBreaking** [comment]
Thx for fixing!
