### ISSUE TITLE
Can't enter negative coordinates

### ISSUE THREAD

**Issue by MightyKnight** [AMereBagatelle/MCG#8]
The title almost says everything already.

When I create a new coordinate and try entering a `-` character for negative numbers, it does not work. Positive numbers create no problems.
Also autodetecting does not fill it in, leaving me unable to create the coordinate.

Using:
- MCG 1.2.1 (Modrinth)
- Fabric API 0.30.0

**Comment by AMereBagatelle** [comment]
This issue was fixed in [this commit](https://github.com/AMereBagatelle/MCG/commit/9db2534eaa627272d2355a7e3d4d159cf4a049b1).
A build will be released soon, I just forgot to.
